---
title: L'istruzione 'Throw' non può omettere l'operando all'esterno di un'istruzione 'Catch' o all'interno di un'istruzione 'Finally'
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: f87c705a8672ba79124c618fbd28e2ef79136b6f
ms.sourcegitcommit: 5c1abeec15fbddcc7dbaa729fabc1f1f29f12045
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 03/15/2019
ms.locfileid: "58026253"
---
# <a name="throw-statement-cannot-omit-operand-outside-a-catch-statement-or-inside-a-finally-statement"></a><span data-ttu-id="0edeb-102">L'istruzione 'Throw' non può omettere l'operando all'esterno di un'istruzione 'Catch' o all'interno di un'istruzione 'Finally'</span><span class="sxs-lookup"><span data-stu-id="0edeb-102">'Throw' statement cannot omit operand outside a 'Catch' statement or inside a 'Finally' statement</span></span>
<span data-ttu-id="0edeb-103">Le istruzioni`Throw` di fuori dell'istruzione `Catch` devono fornire il nome di un oggetto eccezione.</span><span class="sxs-lookup"><span data-stu-id="0edeb-103">`Throw` statements outside of `Catch` statement must supply the name of an exception object.</span></span>  
  
 <span data-ttu-id="0edeb-104">**ID errore:** BC30666</span><span class="sxs-lookup"><span data-stu-id="0edeb-104">**Error ID:** BC30666</span></span>  
  
## <a name="to-correct-this-error"></a><span data-ttu-id="0edeb-105">Per correggere l'errore</span><span class="sxs-lookup"><span data-stu-id="0edeb-105">To correct this error</span></span>  
  
1.  <span data-ttu-id="0edeb-106">Specificare il nome di un oggetto eccezione derivato da `System.Exception`.</span><span class="sxs-lookup"><span data-stu-id="0edeb-106">Specify the name of an exception object derived from `System.Exception`.</span></span>  
  
2.  <span data-ttu-id="0edeb-107">Ristrutturare il codice in modo che l'istruzione `Throw` si trovi in un blocco `Catch` .</span><span class="sxs-lookup"><span data-stu-id="0edeb-107">Restructure your code so that the `Throw` statement is inside a `Catch` block.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="0edeb-108">Vedere anche</span><span class="sxs-lookup"><span data-stu-id="0edeb-108">See also</span></span>

- [<span data-ttu-id="0edeb-109">Istruzione Throw</span><span class="sxs-lookup"><span data-stu-id="0edeb-109">Throw Statement</span></span>](../../visual-basic/language-reference/statements/throw-statement.md)
- [<span data-ttu-id="0edeb-110">Istruzione Try...Catch...Finally</span><span class="sxs-lookup"><span data-stu-id="0edeb-110">Try...Catch...Finally Statement</span></span>](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
- <xref:System.Exception?displayProperty=nameWithType>
- [<span data-ttu-id="0edeb-111">Gestione e generazione di eccezioni in .NET</span><span class="sxs-lookup"><span data-stu-id="0edeb-111">Handling and throwing exceptions in .NET</span></span>](../../standard/exceptions/index.md)
