---
title: L'istruzione 'Throw' non può omettere l'operando all'esterno di un'istruzione 'Catch' o all'interno di un'istruzione 'Finally'
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: 17e7817c608e9c3513e0320b62f42410613f33b0
ms.sourcegitcommit: 9b552addadfb57fab0b9e7852ed4f1f1b8a42f8e
ms.translationtype: MT
ms.contentlocale: it-IT
ms.lasthandoff: 04/23/2019
ms.locfileid: "61666040"
---
# <a name="throw-statement-cannot-omit-operand-outside-a-catch-statement-or-inside-a-finally-statement"></a>L'istruzione 'Throw' non può omettere l'operando all'esterno di un'istruzione 'Catch' o all'interno di un'istruzione 'Finally'
Le istruzioni`Throw` di fuori dell'istruzione `Catch` devono fornire il nome di un oggetto eccezione.  
  
 **ID errore:** BC30666  
  
## <a name="to-correct-this-error"></a>Per correggere l'errore  
  
1. Specificare il nome di un oggetto eccezione derivato da `System.Exception`.  
  
2. Ristrutturare il codice in modo che l'istruzione `Throw` si trovi in un blocco `Catch` .  
  
## <a name="see-also"></a>Vedere anche

- [Istruzione Throw](../../visual-basic/language-reference/statements/throw-statement.md)
- [Istruzione Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
- <xref:System.Exception?displayProperty=nameWithType>
- [Gestione e generazione di eccezioni in .NET](../../standard/exceptions/index.md)
