---
title: Blocco 'Catch' mai raggiunto. <exception> viene gestito sopra nella stessa istruzione 'Try'
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: 3bbb76264ba28f7f74e1ec626adf2c09a50273d4
ms.sourcegitcommit: 9b552addadfb57fab0b9e7852ed4f1f1b8a42f8e
ms.translationtype: HT
ms.contentlocale: it-IT
ms.lasthandoff: 04/23/2019
ms.locfileid: "62003665"
---
# <a name="catch-block-never-reached-exception-handled-above-in-the-same-try-statement"></a>Blocco 'Catch' mai raggiunto. \<eccezione > viene gestito sopra nella stessa istruzione 'Try'
Un blocco `Catch` nel codice non è raggiungibile perché è gestito in un blocco `Try` precedente.  
  
Per impostazione predefinita, si tratta di un messaggio di avviso. Per altre informazioni su come nascondere gli avvisi o considerarli come errori, vedere [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).
  
 **ID errore:** BC42031  
  
## <a name="to-correct-this-error"></a>Per correggere l'errore  
  
- Rimuovere l'istruzione ridondante.  
  
## <a name="see-also"></a>Vedere anche

- [Come usare il blocco try/catch per intercettare le eccezioni](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Uso di gestori eccezioni filtrati dall'utente](../../standard/exceptions/using-user-filtered-exception-handlers.md)
- [Istruzione Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
