---
title: Eccezioni
ms.date: 03/30/2017
ms.assetid: 065205cc-52dd-4f30-9578-b17d8d113136
ms.openlocfilehash: 64a8338133c265ee1b4c7acbd9b4d168318b66a5
ms.sourcegitcommit: 9b552addadfb57fab0b9e7852ed4f1f1b8a42f8e
ms.translationtype: HT
ms.contentlocale: it-IT
ms.lasthandoff: 04/23/2019
ms.locfileid: "61773633"
---
# <a name="exceptions"></a><span data-ttu-id="afd83-102">Eccezioni</span><span class="sxs-lookup"><span data-stu-id="afd83-102">Exceptions</span></span>
<span data-ttu-id="afd83-103">I flussi di lavoro possono usare l'attività <xref:System.Activities.Statements.TryCatch> per gestire le eccezioni generate durante l'esecuzione di un flusso di lavoro.</span><span class="sxs-lookup"><span data-stu-id="afd83-103">Workflows can use the <xref:System.Activities.Statements.TryCatch> activity to handle exceptions that are raised during the execution of a workflow.</span></span> <span data-ttu-id="afd83-104">Queste eccezioni possono essere gestite o generate una seconda volta usando l'attività <xref:System.Activities.Statements.Rethrow>.</span><span class="sxs-lookup"><span data-stu-id="afd83-104">These exceptions can be handled or they can be re-thrown using the <xref:System.Activities.Statements.Rethrow> activity.</span></span> <span data-ttu-id="afd83-105">Le attività della sezione <xref:System.Activities.Statements.TryCatch.Finally%2A> vengono eseguite quando viene completata la sezione <xref:System.Activities.Statements.TryCatch.Try%2A> o <xref:System.Activities.Statements.TryCatch.Catches%2A>.</span><span class="sxs-lookup"><span data-stu-id="afd83-105">Activities in the <xref:System.Activities.Statements.TryCatch.Finally%2A> section are executed when either the <xref:System.Activities.Statements.TryCatch.Try%2A> section or the <xref:System.Activities.Statements.TryCatch.Catches%2A> section completes.</span></span> <span data-ttu-id="afd83-106">I flussi di lavoro ospitato da un <xref:System.Activities.WorkflowApplication> istanza può anche usare il <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> gestore eventi per gestire le eccezioni non gestite da un <xref:System.Activities.Statements.TryCatch> attività.</span><span class="sxs-lookup"><span data-stu-id="afd83-106">Workflows hosted by a <xref:System.Activities.WorkflowApplication> instance can also use the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> event handler to handle exceptions that are not handled by a <xref:System.Activities.Statements.TryCatch> activity.</span></span>  
  
## <a name="causes-of-exceptions"></a><span data-ttu-id="afd83-107">Cause delle eccezioni</span><span class="sxs-lookup"><span data-stu-id="afd83-107">Causes of Exceptions</span></span>  
 <span data-ttu-id="afd83-108">In un flusso di lavoro le eccezioni possono essere generate con le modalità seguenti:</span><span class="sxs-lookup"><span data-stu-id="afd83-108">In a workflow, exceptions can be generated in the following ways:</span></span>  
  
- <span data-ttu-id="afd83-109">Timeout delle transazioni nell'oggetto <xref:System.Activities.Statements.TransactionScope>.</span><span class="sxs-lookup"><span data-stu-id="afd83-109">A time-out of transactions in <xref:System.Activities.Statements.TransactionScope>.</span></span>  
  
- <span data-ttu-id="afd83-110">Eccezione esplicita generata dal flusso di lavoro usando l'attività <xref:System.Activities.Statements.Throw>.</span><span class="sxs-lookup"><span data-stu-id="afd83-110">An explicit exception thrown by the workflow using the <xref:System.Activities.Statements.Throw> activity.</span></span>  
  
- <span data-ttu-id="afd83-111">Eccezione di [!INCLUDE[netfx_current_short](../../../includes/netfx-current-short-md.md)] generata da un'attività.</span><span class="sxs-lookup"><span data-stu-id="afd83-111">A [!INCLUDE[netfx_current_short](../../../includes/netfx-current-short-md.md)] exception thrown from an activity.</span></span>  
  
- <span data-ttu-id="afd83-112">Eccezione generata da codice esterno, ad esempio librerie, componenti o servizi usati nel flusso di lavoro.</span><span class="sxs-lookup"><span data-stu-id="afd83-112">An exception thrown from external code, such as libraries, components, or services that are used in the workflow.</span></span>  
  
## <a name="handling-exceptions"></a><span data-ttu-id="afd83-113">Gestione delle eccezioni</span><span class="sxs-lookup"><span data-stu-id="afd83-113">Handling Exceptions</span></span>  
 <span data-ttu-id="afd83-114">Se un'eccezione viene generata da un'attività ma non viene gestita, il comportamento predefinito prevede l'interruzione dell'istanza del flusso di lavoro.</span><span class="sxs-lookup"><span data-stu-id="afd83-114">If an exception is thrown by an activity and is unhandled, the default behavior is to terminate the workflow instance.</span></span> <span data-ttu-id="afd83-115">Se presente, un gestore personalizzato <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> può eseguire l'override di questo comportamento predefinito.</span><span class="sxs-lookup"><span data-stu-id="afd83-115">If a custom <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is present, it can override this default behavior.</span></span> <span data-ttu-id="afd83-116">Questo gestore consente all'autore dell'host del flusso di lavoro di fornire la gestione appropriata, ad esempio la registrazione personalizzata, l'interruzione, l'annullamento o la chiusura del flusso di lavoro.</span><span class="sxs-lookup"><span data-stu-id="afd83-116">This handler gives the workflow host author an opportunity to provide the appropriate handling, such as custom logging, aborting the workflow, canceling the workflow, or terminating the workflow.</span></span>  <span data-ttu-id="afd83-117">Se un flusso di lavoro genera un'eccezione che non viene gestita, viene chiamato il gestore <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A>.</span><span class="sxs-lookup"><span data-stu-id="afd83-117">If a workflow raises an exception that is not handled, the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="afd83-118">Esistono tre azioni possibili restituite da <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> che determinano il risultato finale del flusso di lavoro.</span><span class="sxs-lookup"><span data-stu-id="afd83-118">There are three possible actions returned from <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> which determine the final outcome of the workflow.</span></span>  
  
- <span data-ttu-id="afd83-119">**Annulla** -un'istanza del flusso di lavoro annullata è una valida uscita di un'esecuzione del ramo.</span><span class="sxs-lookup"><span data-stu-id="afd83-119">**Cancel** - A cancelled workflow instance is a graceful exit of a branch execution.</span></span> <span data-ttu-id="afd83-120">È possibile modellare il comportamento di annullamento, ad esempio usando un'attività CancellationScope.</span><span class="sxs-lookup"><span data-stu-id="afd83-120">You can model cancelation behavior (for example, by using a CancellationScope activity).</span></span> <span data-ttu-id="afd83-121">Il gestore Completed viene richiamato al completamento del processo di annullamento.</span><span class="sxs-lookup"><span data-stu-id="afd83-121">The Completed handler is invoked when the cancellation process completes.</span></span> <span data-ttu-id="afd83-122">Un flusso di lavoro annullato si trova nello stato di annullato.</span><span class="sxs-lookup"><span data-stu-id="afd83-122">A cancelled workflow is in the Cancelled state.</span></span>  
  
- <span data-ttu-id="afd83-123">**Terminare** -un'istanza del flusso di lavoro terminata non può essere ripresa o riavviata.</span><span class="sxs-lookup"><span data-stu-id="afd83-123">**Terminate** - A terminated workflow instance cannot be resumed or restarted.</span></span>  <span data-ttu-id="afd83-124">Ciò attiva l'evento Completed in cui è possibile immettere un'eccezione come motivo del termine dell'istanza.</span><span class="sxs-lookup"><span data-stu-id="afd83-124">This triggers the Completed event in which you can provide an exception as the reason it was terminated.</span></span> <span data-ttu-id="afd83-125">Il gestore Terminated viene richiamato al completamento del processo di chiusura.</span><span class="sxs-lookup"><span data-stu-id="afd83-125">The Terminated handler is invoked when the termination process completes.</span></span> <span data-ttu-id="afd83-126">Un flusso di lavoro terminato si trova nello stato di non riuscito.</span><span class="sxs-lookup"><span data-stu-id="afd83-126">A terminated workflow is in the Faulted state.</span></span>  
  
- <span data-ttu-id="afd83-127">**Interrompi** -un'istanza di flusso di lavoro interrotto può essere ripresa solo se è stato configurato per essere persistente.</span><span class="sxs-lookup"><span data-stu-id="afd83-127">**Abort** - An aborted workflow instances can be resumed only if it has been configured to be persistent.</span></span>  <span data-ttu-id="afd83-128">Senza la persistenza, un flusso di lavoro non può essere ripreso.</span><span class="sxs-lookup"><span data-stu-id="afd83-128">Without persistence, a workflow cannot be resumed.</span></span>  <span data-ttu-id="afd83-129">Nel momento in cui un flusso di lavoro viene interrotto, qualsiasi lavoro eseguito (in memoria) dall'ultimo di punto di persistenza verrà perso.</span><span class="sxs-lookup"><span data-stu-id="afd83-129">At the point a workflow is aborted, any work done (in memory) since the last persistence point will be lost.</span></span> <span data-ttu-id="afd83-130">Per un flusso di lavoro interrotto, viene richiamato il gestore Aborted usando l'eccezione come motivo di quando è stato completato il processo di interruzione.</span><span class="sxs-lookup"><span data-stu-id="afd83-130">For an aborted workflow, the Aborted handler is invoked using the exception as the reason when the abort process completes.</span></span> <span data-ttu-id="afd83-131">Tuttavia, a differenza dei gestori Cancelled e Terminated, il gestore Completed non viene richiamato.</span><span class="sxs-lookup"><span data-stu-id="afd83-131">However, unlike Cancelled and Terminated, the Completed handler is not invoked.</span></span> <span data-ttu-id="afd83-132">Un flusso di lavoro interrotto si trova nello stato di interrotto.</span><span class="sxs-lookup"><span data-stu-id="afd83-132">An aborted workflow is in an Aborted state.</span></span>  
  
 <span data-ttu-id="afd83-133">Nell'esempio seguente viene richiamato un flusso di lavoro che genera un'eccezione.</span><span class="sxs-lookup"><span data-stu-id="afd83-133">The following example invokes a workflow that throws an exception.</span></span> <span data-ttu-id="afd83-134">L'eccezione non viene gestita dal flusso di lavoro e viene richiamato il gestore <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A>.</span><span class="sxs-lookup"><span data-stu-id="afd83-134">The exception is unhandled by the workflow and the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="afd83-135">Gli argomenti <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> vengono controllati per fornire informazioni sull'eccezione e il flusso di lavoro viene terminato.</span><span class="sxs-lookup"><span data-stu-id="afd83-135">The <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> are inspected to provide information about the exception, and the workflow is terminated.</span></span>  
  
 [!code-csharp[CFX_WorkflowApplicationExample#1](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#1)]  
  
### <a name="handling-exceptions-with-the-trycatch-activity"></a><span data-ttu-id="afd83-136">Gestione delle eccezioni con l'attività TryCatch</span><span class="sxs-lookup"><span data-stu-id="afd83-136">Handling Exceptions with the TryCatch Activity</span></span>  
 <span data-ttu-id="afd83-137">La gestione delle eccezioni in un flusso di lavoro viene eseguita con l'attività <xref:System.Activities.Statements.TryCatch>.</span><span class="sxs-lookup"><span data-stu-id="afd83-137">Handling exceptions inside a workflow is performed with the <xref:System.Activities.Statements.TryCatch> activity.</span></span> <span data-ttu-id="afd83-138">L'attività <xref:System.Activities.Statements.TryCatch> dispone di una raccolta <xref:System.Activities.Statements.TryCatch.Catches%2A> di attività <xref:System.Activities.Statements.Catch>, ognuna delle quali è associata a un tipo <xref:System.Exception> specifico.</span><span class="sxs-lookup"><span data-stu-id="afd83-138">The <xref:System.Activities.Statements.TryCatch> activity has a <xref:System.Activities.Statements.TryCatch.Catches%2A> collection of <xref:System.Activities.Statements.Catch> activities that are each associated with a specific <xref:System.Exception> type.</span></span> <span data-ttu-id="afd83-139">Se l'eccezione generata da un'attività contenuta nella sezione <xref:System.Activities.Statements.TryCatch.Try%2A> di un'attività <xref:System.Activities.Statements.TryCatch> corrisponde all'eccezione di un'attività <xref:System.Activities.Statements.Catch%601> nella raccolta <xref:System.Activities.Statements.TryCatch.Catches%2A>, l'eccezione viene gestita.</span><span class="sxs-lookup"><span data-stu-id="afd83-139">If the exception thrown by an activity that is contained in the <xref:System.Activities.Statements.TryCatch.Try%2A> section of a <xref:System.Activities.Statements.TryCatch> activity matches the exception of a <xref:System.Activities.Statements.Catch%601> activity in the <xref:System.Activities.Statements.TryCatch.Catches%2A> collection, then the exception is handled.</span></span> <span data-ttu-id="afd83-140">Se l'eccezione viene generata in modo esplicito una seconda volta oppure viene generata una nuova eccezione, quest'ultima passa fino all'attività padre.</span><span class="sxs-lookup"><span data-stu-id="afd83-140">If the exception is explicitly re-thrown or a new exception is thrown then this exception passes up to the parent activity.</span></span> <span data-ttu-id="afd83-141">Nell'esempio di codice seguente viene mostrata un'attività <xref:System.Activities.Statements.TryCatch> che gestisce un oggetto <xref:System.ApplicationException> generato nella sezione <xref:System.Activities.Statements.TryCatch.Try%2A> da un'attività <xref:System.Activities.Statements.Throw>.</span><span class="sxs-lookup"><span data-stu-id="afd83-141">The following code example shows a <xref:System.Activities.Statements.TryCatch> activity that handles an <xref:System.ApplicationException> that is thrown in the <xref:System.Activities.Statements.TryCatch.Try%2A> section by a <xref:System.Activities.Statements.Throw> activity.</span></span> <span data-ttu-id="afd83-142">Il messaggio dell'eccezione viene scritto nella console dall'attività <xref:System.Activities.Statements.Catch%601>, quindi viene scritto un messaggio nella console nella sezione <xref:System.Activities.Statements.TryCatch.Finally%2A>.</span><span class="sxs-lookup"><span data-stu-id="afd83-142">The exception's message is written to the console by the <xref:System.Activities.Statements.Catch%601> activity, and then a message is written to the console in the <xref:System.Activities.Statements.TryCatch.Finally%2A> section.</span></span>  
  
 [!code-csharp[CFX_WorkflowApplicationExample#33](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#33)]  
  
 <span data-ttu-id="afd83-143">Le attività della sezione <xref:System.Activities.Statements.TryCatch.Finally%2A> vengono eseguite quando viene completata correttamente la sezione <xref:System.Activities.Statements.TryCatch.Try%2A> o <xref:System.Activities.Statements.TryCatch.Catches%2A>.</span><span class="sxs-lookup"><span data-stu-id="afd83-143">The activities in the <xref:System.Activities.Statements.TryCatch.Finally%2A> section are executed when either the <xref:System.Activities.Statements.TryCatch.Try%2A> section or the <xref:System.Activities.Statements.TryCatch.Catches%2A> section successfully completes.</span></span> <span data-ttu-id="afd83-144">La sezione <xref:System.Activities.Statements.TryCatch.Try%2A> viene completata correttamente se non vengono generate eccezioni dal suo interno e la sezione <xref:System.Activities.Statements.TryCatch.Catches%2A> viene completata correttamente se non viene generata o rigenerata alcuna eccezione dal suo interno.</span><span class="sxs-lookup"><span data-stu-id="afd83-144">The <xref:System.Activities.Statements.TryCatch.Try%2A> section successfully completes if no exceptions are thrown from it, and the <xref:System.Activities.Statements.TryCatch.Catches%2A> section successfully completes if no exceptions are thrown or rethrown from it.</span></span> <span data-ttu-id="afd83-145">Se un'eccezione viene generata nella sezione <xref:System.Activities.Statements.TryCatch.Try%2A> section di <xref:System.Activities.Statements.TryCatch> e o non è gestita da un oggetto <xref:System.Activities.Statements.Catch%601> nella sezione <xref:System.Activities.Statements.TryCatch.Catches%2A> o è rigenerata dall'oggetto <xref:System.Activities.Statements.TryCatch.Catches%2A>, le attività in <xref:System.Activities.Statements.TryCatch.Finally%2A> non verranno eseguite a meno che non si verifichi una delle situazioni indicate di seguito.</span><span class="sxs-lookup"><span data-stu-id="afd83-145">If an exception is thrown in the <xref:System.Activities.Statements.TryCatch.Try%2A> section of a <xref:System.Activities.Statements.TryCatch> and is either not handled by a <xref:System.Activities.Statements.Catch%601> in the <xref:System.Activities.Statements.TryCatch.Catches%2A> section, or is rethrown from the <xref:System.Activities.Statements.TryCatch.Catches%2A>, the activities in the <xref:System.Activities.Statements.TryCatch.Finally%2A> will not be executed unless the one of the following occurs.</span></span>  
  
- <span data-ttu-id="afd83-146">L'eccezione è intercettata da un'attività <xref:System.Activities.Statements.TryCatch> di livello superiore nel flusso di lavoro, indipendentemente che sia rigenerata da quell'attività <xref:System.Activities.Statements.TryCatch> di livello superiore.</span><span class="sxs-lookup"><span data-stu-id="afd83-146">The exception is caught by a higher level <xref:System.Activities.Statements.TryCatch> activity in the workflow, regardless of whether it is rethrown from that higher level <xref:System.Activities.Statements.TryCatch>.</span></span>  
  
- <span data-ttu-id="afd83-147">L'eccezione non è gestita da un'attività <xref:System.Activities.Statements.TryCatch> di livello superiore, ignora la radice del flusso di lavoro e il flusso di lavoro è configurato per l'annullamento anziché per la chiusura o l'interruzione.</span><span class="sxs-lookup"><span data-stu-id="afd83-147">The exception is not handled by a higher level <xref:System.Activities.Statements.TryCatch>, escapes the root of the workflow, and the workflow is configured to cancel instead of terminate or abort.</span></span> <span data-ttu-id="afd83-148">I flussi di lavoro ospitati usando <xref:System.Activities.WorkflowApplication> possono configurare queste operazioni gestendo <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> e restituendo <xref:System.Activities.UnhandledExceptionAction.Cancel>.</span><span class="sxs-lookup"><span data-stu-id="afd83-148">Workflows hosted using <xref:System.Activities.WorkflowApplication> can configure this by handling <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> and returning <xref:System.Activities.UnhandledExceptionAction.Cancel>.</span></span> <span data-ttu-id="afd83-149">Un esempio di gestione di <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> è stato fornito in precedenza in questo argomento.</span><span class="sxs-lookup"><span data-stu-id="afd83-149">An example of handling <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> is provided previously in this topic.</span></span> <span data-ttu-id="afd83-150">I servizi flusso di lavoro possono configurare queste operazioni usando <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior> e specificando <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionAction.Cancel>.</span><span class="sxs-lookup"><span data-stu-id="afd83-150">Workflow services can configure this by using <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior> and specifying <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionAction.Cancel>.</span></span> <span data-ttu-id="afd83-151">Per un esempio di configurazione <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior>, vedere [Workflow Service Host Extensibility](../wcf/feature-details/workflow-service-host-extensibility.md).</span><span class="sxs-lookup"><span data-stu-id="afd83-151">For an example of configuring <xref:System.ServiceModel.Activities.Description.WorkflowUnhandledExceptionBehavior>, see [Workflow Service Host Extensibility](../wcf/feature-details/workflow-service-host-extensibility.md).</span></span>  
  
## <a name="exception-handling-versus-compensation"></a><span data-ttu-id="afd83-152">Gestione delle eccezioni e compensazione</span><span class="sxs-lookup"><span data-stu-id="afd83-152">Exception Handling versus Compensation</span></span>  
 <span data-ttu-id="afd83-153">La gestione delle eccezioni si verifica durante l'esecuzione di un'attività,</span><span class="sxs-lookup"><span data-stu-id="afd83-153">The difference between exception handling and compensation is that exception handling occurs during the execution of an activity.</span></span> <span data-ttu-id="afd83-154">mentre la compensazione si verifica dopo il corretto completamento di un'attività.</span><span class="sxs-lookup"><span data-stu-id="afd83-154">Compensation occurs after an activity has successfully completed.</span></span> <span data-ttu-id="afd83-155">La gestione delle eccezioni consente di eseguire una pulizia dopo che l'attività genera l'eccezione, mentre la compensazione permette di annullare il lavoro correttamente completato di un'attività portata a termine in precedenza.</span><span class="sxs-lookup"><span data-stu-id="afd83-155">Exception handling provides an opportunity to clean up after the activity raises the exception, whereas compensation provides a mechanism by which the successfully completed work of a previously completed activity can be undone.</span></span> <span data-ttu-id="afd83-156">Per altre informazioni, vedere [compensazione](compensation.md).</span><span class="sxs-lookup"><span data-stu-id="afd83-156">For more information, see [Compensation](compensation.md).</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="afd83-157">Vedere anche</span><span class="sxs-lookup"><span data-stu-id="afd83-157">See also</span></span>

- <xref:System.Activities.Statements.TryCatch>
- <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A>
- <xref:System.Activities.Statements.CompensableActivity>
